#include<stdio.h>
#include<conio.h>
#include<iostream.h>
main()
{
cout<<"NAMA         :Alsyan Fahri Hasibuan";
cout<<"kelas        :X RPL-2";
cout<<"Tempatlahir  :Medan";
cout<<"tanggal lahir:03 agustus 1999";
cout<<"asal sekolah :SMP DARUSSALAM MEDAN";
cout<<"Agama        :ISLAM";
cout<<"No Handphone :087869587787";
cout<<"Visi saya    :akan menjadi siswa yang baik dari yang terbaik";
cout<<"Misi saya    :satyaku kudharmakan dharmaku kubaktikan";
cout<<"cita-cita    :ABRI";
return 0;
}